language: scala
jdk:
  - openjdk8

scala:
 - 2.11.12
 - 2.12.9

cache:
  directories:
    - $HOME/.ivy2

env:
  - LIFT_VERSION=3.3.0
  - LIFT_VERSION=3.2.0
  - LIFT_VERSION=3.1.1
  - LIFT_VERSION=3.0.2

# Add a spritz of 2.6 build.
matrix:
  include:
    - scala: 2.11.12
      env: LIFT_VERSION=2.6.3

script: ./travis.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ab0619f0b7e5b623966a
    on_success: always
    on_failure: always
    on_start: never
