language: scala
jdk:
  - oraclejdk8

scala:
 - 2.11.12
 - 2.12.4

cache:
  directories:
    - $HOME/.ivy2

branches:
  only:
    - master

script: ./travis.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ab0619f0b7e5b623966a
    on_success: always
    on_failure: always
    on_start: never
